location: .gitman
sources:
  - name: pcl
    type: git
    repo: https://github.com/PointCloudLibrary/pcl.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - name: pcl
    type: git
    repo: https://github.com/PointCloudLibrary/pcl.git
    sparse_paths:
      -
    rev: cbed174ba0a0c9ef021015d54d3b60320d808593
    link:
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
