method: # [FPFH, NDT, GICP, ICPN, SICPN]
  initial: 4
  fine_tune: 3

use_init_guess: false
normal_estimation_radius: 0.2
min_convergence_score: 0.5

preprocess:
  voxel_leaf: 0.05
  ror:
    radius: 1.0
    neighbors: 5

cloud_correlation:
  method: "polyline_barycenter" # [polyline_barycenter, centroid]
  z_crop_offset: 2.0

  polyline_barycenter:
    hull: "concave" # [concave, convex]
    concave:
      alpha: 2.0

icpn:
  max_corr_dist: 4.0
  ransac_outl_rej_thrd: 0.95
  trans_ep: 0.01
  eucld_fitn_eps: 0.01
  max_iter: 1000
  ransac_iter: 300
  use_recip_corr: false

sicpn:
  number_of_samples: 8
  max_corr_dist: 7.0
  ransac_outl_rej_thrd: 0.8
  trans_ep: 0.01
  eucld_fitn_eps: 0.01
  max_iter: 1000
  ransac_iter: 300
  use_recip_corr: false
