scope_timer:
  enable: false
  log_filename: ""

lidar3d:

  name:      "ouster"
  frequency: 10       # [Hz]
  vfov:      90       # [deg]

  republish: true
  keep_organized: true

  clip:
    range:
      use: true
      min: 1.1  # [m]
      max: 40.0 # [m]
    intensity:
      use: false
      threshold: 35
      range: 5.0
    reflectivity:
      use: false
      threshold: 25
      range: 5.0

  cropbox:
    use: false
    crop_inside: false # if true, points inside the box will be cropped, otherwise points outside will be cropped
    frame_id: rtk_origin
    min: [-32.0, -35.0, 6.0]
    max: [35.0, 5.0, 19.0]

  ground_removal:
    use: false
    range:
      use: true
    static_frame_id: gps_origin
    max_precrop_height: 2.0
    ransac:
      max_inlier_distance: 0.5
    offset: 1.0
    publish_plane_marker: true

  cloud_filter:
    sequence: ["voxel_grid", "NormS"] # sequence of filters to be applied (in this order) | example: ["voxel_grid", "NormS"]

    downsample:        # basically binning
      row_step: 1      # binning step in row dimension
      col_step: 1      # binning step in column dimension
      dynamic_row_selection: false # [experimental]

    voxel_grid:      # uniform sampling
      resolution: 0.05 # (m) | voxel size

    NormS:                    # Rusinkiewicz and Levoy, Efficient Variants of the ICP Algorithm, 2001
      resolution:
        azimuth:   !degrees 5 # (rad)
        elevation: !degrees 5 # (rad)

    CovS:               # Gelfand et. al, Geometrically stable sampling for the ICP algorithm, 2003
      count: 5000       # <0, max(unsigned int)) | number of points to sample
      torque_norm: "L1" # {L1, Lavg}             | method of torque normalization

rplidar:
  republish: false
