lidar3d:

  name:      "ouster"
  frequency: 10.0 # [Hz]
  vfov:      90.0 # [deg]

  republish: true
  keep_organized: true

  invalid_value: -42.0 # [-42.0 => NaN]

  clip:

    range:
      use: false
      min: 1.1  # [m]
      max: 40.0 # [m]

    intensity:
      use: false
      threshold: 100.0 # 100.0 # points below this intensity beyond the range will be filtered out <0, 100000000>
      range: 5.0       # points beyond this the range below the intensity will be filtered out <0, 100000000>

    reflectivity:
      use: false
      threshold: 25
      range: 5.0

  cropbox:
    use: false
    crop_inside: false # if true, points inside the box will be cropped, otherwise points outside will be cropped
    frame_id: rtk_origin
    min: [-32.0, -35.0, 6.0]
    max: [35.0, 5.0, 19.0]

  downsampling:
    row_step: 1
    col_step: 1

    dynamic_row_selection: false
    dynamic_row_offset: 0

scope_timer:
  enable: false
  log_filename: ""
