depth:
  camera_names: ["up_rgbd", "down_rgbd"]

  up_rgbd:

    topic:
      depth_in: "up_rgbd/depth/image_rect_raw"
      depth_camera_info_in: "up_rgbd/depth/camera_info"
      points_out: "up_rgbd/points_processed"
      points_over_max_range_out: "up_rgbd/points_over_max_range" # used if non-empty and range_clip used

    filter:
      downsample:
        step:
          row: 2 # used if >1
          col: 2 # used if >1
      range_clip:
        min: 0.4
        max: 10.0 # used if >0
      voxel_grid:
        resolution: 0.05 # used if >0
      radius_outlier:
        radius: 0.0 # used if both >0
        neighbors: 2
      minimum_grid:
        resolution: 0.05 # used if >0
      bilateral:
        sigma_S: 0.0 # used if both >0
        sigma_R: 0.005

  down_rgbd:

    topic:
      depth_in: "down_rgbd/depth/image_rect_raw"
      depth_camera_info_in: "down_rgbd/depth/camera_info"
      points_out: "down_rgbd/points_processed"
      points_over_max_range_out: "down_rgbd/points_over_max_range" # used if non-empty and range_clip used

    filter:
      downsample:
        step:
          row: 2 # used if >1
          col: 2 # used if >1
      range_clip:
        min: 0.4
        max: 10.0 # used if >0
      voxel_grid:
        resolution: 0.05 # used if >0
      radius_outlier:
        radius: 0.0 # used if both >0
        neighbors: 5
      minimum_grid:
        resolution: 0.05 # used if >0
      bilateral:
        sigma_S: 0.0 # used if both >0
        sigma_R: 0.005
